[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "12"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  
  [[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
